### ISSUE TITLE
Add a Gen for Enum values

### ISSUE THREAD

**Issue by ColinHebert** [kotlintest/kotlintest#124]
There is no nice way to get a `Gen` for enums.
Unfortunately the current version of Kotlin (1.0.5), does not support iterating over the values of an enum class specified as a generic.

The good news is that it is supported from Kotlin 1.1-M3, see https://github.com/Kotlin/KEEP/blob/master/proposals/generic-values-and-valueof-for-enums.md and https://youtrack.jetbrains.com/issue/KT-10569

The fix is trivial with newer versions of kotlin:
```kotlin
inline fun <reified T : Enum<T>> oneOf() = oneOf(enumValues<T>().toList())
```

This allows developers to do the following:
```kotlin
enum class MyEnum { ENTRYA, ENTRYB }

Gen.oneOf<MyEnum>().generate()
```

**Comment by sksamuel** [comment]
If you make this PR against the v2.0 branch, I'm happy for that to be 1.1+
@helmbold you agree?

**Comment by helmbold** [comment]
I like the extension for enums. I expect Kotlin 1.1 to be released at the beginning of 2017, so it shouldn't be an issue to couple KotlinTest 2.0 with Kotlin 1.1. If Kotlin 1.1 would be delayed unexpectedly so that we our release would be delayed too, we could push this change to 3.0, so it is low risk to include it now.

**Comment by sksamuel** [comment]
Can't be much longer for 1.1 surely, been a long time already.

**Comment by sksamuel** [comment]
Added
