### ISSUE TITLE
README showing "old style" init-based StringSpec

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#177]
Should the README show the newer style of StringSpec where the block is in the superclass constructor rather than an explicit init block?

**Comment by sksamuel** [comment]
It's just a matter of preference rather than one being better I think. Personally I prefer the init block.

**Comment by russel** [comment]
OK, no problem. Can you tell us the reason for your preference for init over construction? (I want to present the most idiomatic KotlinTest code possible at DevoxxUK 2017 on Thursday.)

**Comment by russel** [comment]
@sksamuel I just reread https://discuss.kotlinlang.org/t/init-block-for-constructor-body/1703 does the above comment mean you have changed your position on the superclass constructor and init blocks? Fine if yes, I am just worrying about showing the most idiomatic code – but I already said that above I guess.

**Comment by sksamuel** [comment]
In that discussion I was arguing we should just be able to do,

```kotlin
class MyClass {
  val writer = new Writer
  writer.write("start")
  fun foo = ...
}
```

and dispense with the init block entirely.

But as to your question, we don't have a position on which is clearer. I'm not even sure which style most people use. I use the init block purely because that's just the way I've always done it. If we had to pick I'd say the init block was the idiomatic way. @helmbold may have a stronger opinion.

**Comment by helmbold** [comment]
@sksamuel :-)
@russel If I had to define what most idiomatic, or "kotlinic", code would look like in this case, I'd say `init`. Actually I consider the block-passed-to-super-class-constructor-style a hack to come close to Scala syntax. Technically the test definition is part of the initialization and this is exactly the puropose of the `init` block.

**Comment by russel** [comment]
Thanks. That works for me. I shall switch back to init blocks.
