### ISSUE TITLE
shouldEqual may fail on data class with ByteArray property

### ISSUE THREAD

**Issue by Vanco** [kotlintest/kotlintest#191]
When to data class A, B compared with Matcher, it should check content only.  But if data class has ByteArray property. the shouldEqual will fail.  

e.g.
```
data class Simple(val name: String, val age: Int)
data class WithByteArray(val name: String, val age: Int, val niknames: ByteArray)

class DataClassSpec : StringSpec() {
    init {
        "Simple data class should equal " {
            val a = Simple("Apple", 23)
            val b = Simple("Apple", 23)

            a shouldEqual b
        }

        "WithArrayField data class should equal " {
            val a = WithByteArray("Apple", 23, "Big Apple".toByteArray())
            val b = WithByteArray("Apple", 23, "Big Apple".toByteArray())

            a shouldEqual b
        }
    }
}
```

the second test failed.

**Comment by helmbold** [comment]
What version of KotlinTest are you using?

**Comment by Vanco** [comment]
I'm using 'io.kotlintest:kotlintest:2.0.4'.

**Comment by sksamuel** [comment]
It's a tricky one because ByteArray is just an array, and arrays on the JVM don't implement deep equals, they just check for identity. So if you use byte array in a data class for example, we'd have to override the equals method generated. I think this is just something you have to work around by testing the values individually.
https://stackoverflow.com/questions/8051084/java-how-to-test-on-array-equality
