### ISSUE TITLE
afterAll() on project is wrong - it seems to fire once after first spec

### ISSUE THREAD

**Issue by adz** [kotlintest/kotlintest#201]
https://github.com/kotlintest/kotlintest/blob/674c5dd790395680b99e056f7df2c0869f6d932a/src/main/kotlin/io/kotlintest/Project.kt#L33

This looks like the afterAll() on Project will run after the first spec and for no subsequent ones.

**Comment by sksamuel** [comment]
Seems afterAll is indeed wrong, it will fire once as soon as the first spec completes as @adz has pointed out. @helmbold any ideas on how to implement this correctly.

**Comment by sksamuel** [comment]
Ok I've pushed a fix. It might be a bit hacky, but it seems to work. Each time a test runner is created, we increment the count. After each test runner, we check the count to see if the total count == completed count. Then, as long as another test runner isn't created within 5 seconds (this is the hacky part), then it is executed. The reason for this is because test runners are not all created in advance, and there is no way (that I can see, been looking for an hour), of getting the total number of test suites in advance. (Maybe junit 5 offers something better, but I'm reluctant to move to that until the reports of issues have gone away.)

I've also removed the synchronised calls on afterAll and beforeAll because you don't need them with atomics.

**Comment by helmbold** [comment]
I'm not happy with the waiting, too. I think (hope) that JUnit 5 will help. See [EngineExecutionListener](http://junit.org/junit5/docs/current/api/org/junit/platform/engine/EngineExecutionListener.html)

**Comment by sksamuel** [comment]
See the PR that's awaiting you. It's fixed properly in that.

**Comment by sksamuel** [comment]
This is fixed properly in 3.0.0 RC1.

AfterAll now fires once properly.
If you have the time, please give it a try.

There are some breaking changes that should be aware of which are covered by the changelog.
https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
