### ISSUE TITLE
shouldNotThrow and shouldNotThrowAny matchers

### ISSUE THREAD

**Issue by myhau** [kotlintest/kotlintest#205]
Having these matchers would be great 
-`shouldNotThrow` 
-`shouldNotThrowAny`

Currently there is not way of expressing that easily with kotlintest matchers

**Comment by helmbold** [comment]
Good idea! However `shouldNotThrowAny` should not be needed, since that is the default case implicitly assumed in all test cases. Or what would be the use case for this matcher?

**Comment by myhau** [comment]
2 reasons that I can think of now:
- I think tests are more readable if you explicitly write `shouldNotThrowAny`
- assertion error can more precisely tell you why your test failed: "you expected no exception, but we found: `SomethingException`"

**Comment by philipwhiuk** [comment]
> assertion error can more precisely tell you why your test failed: "you expected no exception, but we found: SomethingException"

Isn't this just an extremely verbose way of writing "Unexpected exception: SomethingException" and why can't we do this for every exception.

**Comment by sksamuel** [comment]
We already log when an exception happens and it shouldn't,

`java.lang.RuntimeException: boo`

So that's that covered. I agree with @helmbold I don't see a valid use case for this because every method should not throw an exception unless otherwise specified.

**Comment by TAGC** [comment]
I think `shouldNotThrow` is a good idea, because it makes the code more explicit. Testing libraries like Shouldly support these assertions.

**Comment by Kerooker** [comment]
@TAGC Would you mind creating an issue for that? I agree with you that syntax would be prettier and human-readable.

Althought technically, if your code doesn't throw any exception, you're already asserting that it doesn't throw anything

**Comment by Kerooker** [comment]
@sksamuel 
Sometimes users want to write things in a more explicitly.

It's the same reason we added the matchers
`shouldNotBeTrue` and `shouldNotBeFalse` https://github.com/kotlintest/kotlintest/issues/452

Of course `(3 ==3).shouldBeTrue` is exactly the same as `(3==3).shouldNotBeFalse`, but sometimes one might want to say in a way or another.

Adding a `shouldNotThrow` empty block doesn't look like a problem to me, and it won't make users more confused

**Comment by TAGC** [comment]
> @TAGC Would you mind creating an issue for that? I agree with you that syntax would be prettier and human-readable.

Not sure what you mean. Why create a new issue for the same proposal as this one?

> What's the difference except more noise ?

In short test-cases, it probably does create more noise than it's worth. For example, it my case instead of:

```kotlin
it("can be connected to other ports of a supertype") {
    val derivedPort = createDummy<Derived>()
    val basePort = createDummy<Base>()
    derivedPort join basePort
}
```

I might write:

```kotlin
it("can be connected to other ports of a supertype") {
    val derivedPort = createDummy<Derived>()
    val basePort = createDummy<Base>()
    shouldNotThrow { derivedPort join basePort }
}
```

And it wouldn't make much difference.

However, in longer test-cases the advantage is that it helps distinguish the assertion from the rest of the setup/cleanup code.

```kotlin
it("verifies something") {
    val x = Foo()
    x.bar()
    x.baz()
    // More setup for x
    
    val y = Foo2()
    y.bar(x)
    y.baz(x)
    // More setup for y
    
    y.baz(z)
    
    cleanup(x)
    cleanup(y)
    // More cleanup
}
```

vs. 

```kotlin
it("verifies something") {
    val x = Foo()
    x.bar()
    x.baz()
    // More setup for x

    val y = Foo2()
    y.bar(x)
    y.baz(x)
    // More setup for y

    shouldNotThrow { y.baz(z) }

    cleanup(x)
    cleanup(y)
    // More cleanup
}
```

Without this assertion, I might be inclined to write `y.baz(z) // should not throw`, but that's not as good for the reason why comments in general are not preferable to readable code: because comments can become stale, they can lie, but code never lies.

Furthermore, if you just write the assertion as a plain statement and it fails, all you get is a regular stacktrace associated with the unit test, indistinguishable in structure from the stacktraces you'd get if any other part of the test (setup/cleanup) failed. A `shouldNotThrow` can instead capture exceptions and rethrow them with a message like "Expected no exception to be thrown, but \<wrapped exception\> was thrown".

In the same way that the `shouldNotThrow` statement helps visually distinguish the *assertion code* from the rest of test code (making the test more readable), the exception it throws can help distinguish an *assertion failure* from any other failure within the code (making the problem easier to understand and the bug easier to fix).

It's an especially nice assertion to have when you have some function that should throw exceptions under certain circumstances and shouldn't throw in others, and you want test both types of scenarios. That leads to nice symmetrical code:

```c#
public void Message_Decoder_Should_Decode_Additional_Messages_After_Decoding_Complete_And_After_Reset()
{
    // GIVEN a mock decoder that is able to decode messages and has completed decoding.
    var mockDecoder = new MockMessageDecoder
    {
        DecodingMessagesAllowed = true
    };
    mockDecoder.SetDecodingComplete();

    // WHEN we reset the mock decoder.
    mockDecoder.Reset();

    // THEN we should be able to decode more messages.
    Should.NotThrow(() => mockDecoder.DecodeMessage(default(GenericMessage)));
}

[Fact]
public void Message_Decoder_Should_Decode_No_Additional_Messages_After_Decoding_Complete_And_Before_Reset()
{
    // GIVEN a mock decoder that can decode messages.
    var mockDecoder = new MockMessageDecoder
    {
        DecodingMessagesAllowed = true
    };

    // WHEN decoding is complete.
    mockDecoder.SetDecodingComplete();

    // THEN an exception should be thrown when trying to decode another message.
    Should.Throw<InvalidOperationException>(() => mockDecoder.DecodeMessage(default(GenericMessage)));
}
```

**Comment by grodin** [comment]
I was just looking for this. Can the issue be reopened please?

**Comment by LeoColman** [comment]
Reopened.

As we discussed some points, I think this is still valid:

1. All matchers have a `not` option. Why `shouldThrow` doesn't?
2. There's no harm in adding this, as nobody will be forced to use, and no code will break due to this

**Comment by LeoColman** [comment]
However, we should work on the syntax a bit.

```
"FooTest" {
    shouldNotThrow<FooException> {
        throw BarException()
    }
}
```

Should this test pass? Or it shouldn't throw `BarException` either?

**Comment by LeoColman** [comment]
This can lead to a confusing scenario, in which the test passes due to eating an exception. I think that if the test throws `FooException` it should be yellow, as the assertion failed. If it throws `BarException`, it should FAIL, as there was no scope for the captured exception.

This should also go for any of the scopes.

**Comment by sksamuel** [comment]
I think this is pointless. It would be like Java having to put a "does not throw" on every method.

```java
public void processString(String str) throws no exception {
}
```

Unless declared otherwise a test must not throw.

But... if you really want to add it, add it. But leave it as a hidden feature as I think advertising it is a bit silly.

**Comment by LeoColman** [comment]
It is pointless in a way, but instead of Erroring a test we will fail it. Might have a different semantic for people. Something like "It wasn't an error. It was a bad implementation of some logic".

And technically, we're already advertising it. The [matchers page](https://github.com/kotlintest/kotlintest/blob/master/doc/matchers.md) clearly states
>Matchers can be negated by using shouldNot instead of should for the infix style. For example, a shouldNot startWith("boo"). For the extension function style, each function has an equivalent negated version, for example, a.shouldNotStartWith("boo").

I think this kind of matcher is good to show that "Ok, usually this block of codes throws an error. But we explicitly don't want it to throw an error here".

It won't hurt :P

**Comment by LeoColman** [comment]
I probably won't ever use it in any projects tho, but who knows

**Comment by sksamuel** [comment]
It won't hurt, that's why I'm not against it, as generally speaking I think cest la vie.
But I would be against advertising it as the idiomatic way.

**Comment by sksamuel** [comment]
Does any other assertion library in any other language offer this ?

**Comment by LeoColman** [comment]
Not that I've ever seen.

**Comment by LeoColman** [comment]
However, there's a big discussion in StackOverflow about this
https://stackoverflow.com/questions/17731234/how-to-test-that-no-exception-is-thrown

**Comment by LeoColman** [comment]
And
https://stackoverflow.com/questions/8575653/how-can-i-test-if-a-particular-exception-is-not-thrown

**Comment by LeoColman** [comment]
And to be honest, my implementation is just running `block` and wrapping any exception in an `AssertionError`

**Comment by sksamuel** [comment]
https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertDoesNotThrow(org.junit.jupiter.api.function.Executable)

**Comment by LeoColman** [comment]
There's precedence then

**Comment by TAGC** [comment]
> Does any other assertion library in any other language offer this ?

@sksamuel I mentioned earlier that [Shouldly does.](http://docs.shouldly-lib.net/docs/shouldnotthrow) It's a popular C# test assertion library.

**Comment by sksamuel** [comment]
Fair enough. And I found that JUnit does as well.

**Comment by LeoColman** [comment]
Working on it.

**Comment by LeoColman** [comment]
@TAGC please take a look at the latest PR. It should be released on the next release.

**Comment by TAGC** [comment]
Yeah looks good, thanks.
