### ISSUE TITLE
IoU a beer

### ISSUE THREAD

**Issue by pakoito** [kotlintest/kotlintest#265]
@sksamuel  I see from your profile that you live in London and also like beer. The library is awesome and has helped Arrow immensely, so you get a free beer from us anytime :D

**Comment by sksamuel** [comment]
Yeah man I live in Wembley. KotlinTest is just a small library. Arrow is the awesome library that's making Kotlin a real alternative to things like Scala.

**Comment by pakoito** [comment]
After following your issues for several days, I'm pretty sure you're the largest most used library. And you definitely need a beer :D Hit me up whenever you want!

**Comment by sksamuel** [comment]
Been meaning to add these for a while, but have started adding Arrow matchers.
https://github.com/kotlintest/kotlintest/blob/master/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/assertions/arrow/EitherMatchersTest.kt

**Comment by sksamuel** [comment]
https://github.com/kotlintest/kotlintest/blob/master/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/assertions/arrow/OptionMatchersTest.kt

**Comment by raulraja** [comment]
We should refactor the Arrow tests to include these new matchers for sure! 

@sksamuel is there room in this new module for `Functor`, `Applicative`, `Monad` instances for `Gen` so we can use Arrow monad comprehensions and applicative builders to build generic generated values for arbitrary types inside type constructors such as `IO`, `Deferred`, etc... ? 

I had at some point a `GenK` wrapper that I was using to encode polymorphic programs over any `F`:

```
fun <F> Applicative<F>.program(): Gen<Kind<F, Int>> = Gen.create { just(Gen.int().generate()) }

forAll(Option.applicative().program()) { fa: Option<Int> -> TODO() }
forAll(IO.applicative().program()) { fa: IO<Int> -> TODO() }
forAll(Either.applicative<Throwable>().program()) { fa: Either<Throwable, Int> -> TODO() }
```

This would enable us to encode abstract generators in terms of `Applicative` and `Monad` that could be used for any of the data types that provide instances for those which are a lot including integrations with popular libraries such as Rx2, Kotlin Coroutines, etc.

**Comment by sksamuel** [comment]
Yes I don't see why not. This module depends on arrow's typeclass and data dependencies so anything they provide can be used. I could add effect also if needed.

**Comment by raulraja** [comment]
Awesome! let us knows if you want us to help with contributions or clarify anything related to Arrow. Reading this issue made my day! :beers:

**Comment by raulraja** [comment]
Completely unrelated, I once wrote a REST backend to https://github.com/sksamuel/scrimage for fun

**Comment by sksamuel** [comment]
Did you. That's pretty cool. Do you know why I wrote scrimage originally.

**Comment by raulraja** [comment]
It was a Play app to do stuff like 
```
images/transform/c_thumb:150:150,c_limit:150:150/image.png?url=remoteimage
```
Had most effects and params encoded in a single url and could cache, load and act as proxy to `scrimage`

**Comment by sksamuel** [comment]
That's briliant. So I host a pub quiz (trivia night) at my local pub. And I wanted to do really neat picture rounds based on quiz shows. So that was the basis for the library. It allowed me to write programs to generate these picture rounds from raw unsized/unprocessed images. Otherwise it was far too time consuming.

![robots](https://user-images.githubusercontent.com/743706/38397699-10e2efc2-3937-11e8-8992-a7dd9a6912f2.jpeg)
![moviecars](https://user-images.githubusercontent.com/743706/38397701-137d98f4-3937-11e8-8824-772980e2d248.jpeg)
![blockbuster_sample_output](https://user-images.githubusercontent.com/743706/38397710-1e00ca94-3937-11e8-8a6e-cec9c485a856.jpg)
![june22](https://user-images.githubusercontent.com/743706/38397714-23eaed5e-3937-11e8-8971-e6c686c18166.jpeg)
![picnmix_final](https://user-images.githubusercontent.com/743706/38397721-29cb128a-3937-11e8-8b45-d009a07383a0.jpeg)
![picnmix_final](https://user-images.githubusercontent.com/743706/38397724-2ce7bd10-3937-11e8-9374-bc6d1c7e4755.jpeg)
![backpacking around the world on your gap year](https://user-images.githubusercontent.com/743706/38397732-39eb907c-3937-11e8-982d-76bc349042f1.jpg)

**Comment by sksamuel** [comment]
`Try` matchers added. Closing issue as preparing for 3.1 snapshot.

**Comment by pakoito** [comment]
B-b-b-but the beer.

**Comment by sksamuel** [comment]
Definitely. I'm away in Japan from Thursday but once I'm back ? Are you going to KotlinConf btw? I'm tempted to submit a talk on KotlinTest.

**Comment by pakoito** [comment]
Sure, find me here, on gitter, or on Slack! 

Please do submit the talk, it's a really good library :D As for myself, I still haven't figured out what to send that doesn't conflict with the other maintainers', and if I don't speak I probably won't get the time off to attend.

**Comment by sksamuel** [comment]
Any suggestions on what you think might be a good part of the library to talk about. Standard unit tests is a bit passe I think.

**Comment by pakoito** [comment]
Property-based testing is a novel concept in the Android world. Have something like [this](http://arrow-kt.io/docs/generic/product/) mentioned or in the lib and you have an upper hand over every other competitor.

**Comment by sksamuel** [comment]
In what way? Using product in property testing to allow arbitrary testing of any data class ?

**Comment by sksamuel** [comment]
From a `Tuple2` or `HList` can I get the types of the arguments?

**Comment by sksamuel** [comment]
What would be most useful in testing is,

```
assertAll<Account> {
  it.name shouldBe "wibble"
  it.id shouldBe gt(0)
}
```

Allowing the library to build you an account from base generators automatically, instead of manually supplying the generator types, like I have here:
https://github.com/kotlintest/kotlintest/blob/master/kotlintest-assertions/src/main/kotlin/io/kotlintest/properties/Gen.kt#L128-L210

For that to work, I'd need to be able to turn the `Account` into a tuple (maybe the user has to supply that).

**Comment by pakoito** [comment]
You can try with extfuns and inline, they're resolved statically and allow for partially applied generics.

```kotlin
fun <A> Tuple2<Int, A>.thing() = 1 

fun <A> Tuple2<String, A>.thing() = 12

Tuple2(1, "1").thing()
// 1

Tuple2("1", "1").thing()
// 12
```
