### ISSUE TITLE
io.kotlintest.properties 2.0 → 3.[01]

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#310]
Hi,

I have some tests that run fine with 2.0.x. I change the Gradle build file to swap from the single artefact to the trio of artefacts for 3.1.X but now:
```kotlin
import io.kotlintest.properties.table
import io.kotlintest.properties.headers
import io.kotlintest.properties.row
```
are unfound. I can't see anything about this in the 3.0 release notes, but maybe I am just missing it?

I am using Gradle 4.7 on Debian Linux.

**Comment by sksamuel** [comment]
They do exist. 
https://github.com/kotlintest/kotlintest/blob/master/kotlintest-assertions/src/main/kotlin/io/kotlintest/tables/TableTesting.kt

Are you definitely bringing in `kotlintest-assertions`?
Although if you add the junit5 artifact the rest should come down automatically.

**Comment by russel** [comment]
In my build.gradle.kts:
```kotlin
dependencies {
	compile(kotlin("stdlib"))
	//testCompile("io.kotlintest:kotlintest:2.+")
	testCompile("io.kotlintest:kotlintest-core:3.+")
	testCompile("io.kotlintest:kotlintest-assertions:3.+")
	testCompile("io.kotlintest:kotlintest-runner-junit5:3.+")
}
```

**Comment by sksamuel** [comment]
You only need testCompile("io.kotlintest:kotlintest-runner-junit5:3.+")

But  it should still have worked. Maybe intellij isn't picking it up properly.

**Comment by russel** [comment]
This is from the command line.

The code is Factorial :-)  

https://github.com/russel/Factorial/tree/master/Kotlin

(Still the 2.+ build file.)

**Comment by sksamuel** [comment]
Ok so a few issues here.

You're using the Kotlin DSL for gradle which inside intellij won't support junit 5 declaration.
But the rest needs to be set like this:

```kotllin
plugins {
	`kotlin-dsl`
}

repositories {
	jcenter()
	mavenCentral()
}

tasks {
  withType<Test>{
 //   useJUnitPlatform()
  }
}

dependencies {
	compile(kotlin("stdlib"))
	testCompile("io.kotlintest:kotlintest-runner-junit5:3.0.6")
}

defaultTasks("test")
```

Then refresh gradle from within intellij and the dependencies will work properly.

The imports for the table testing has changed to io.kotlintest.tables.xxx.

There seems to be an issue if you want to use table testing with properly testing as it can't work out which forall method to use because they're in different packages. I'd open up that as a bug and I'll add a workaround in.

**Comment by russel** [comment]
Pushed changes that seem to make things work fine using Gradle 4.7 and Kotlintest 3.1.0.

**Comment by sksamuel** [comment]
Great. I'll close this then as ticket #311 covers the import issue.
