### ISSUE TITLE
Title for Wordspec tests is missing context

### ISSUE THREAD

**Issue by dhoepelman** [kotlintest/kotlintest#473]
I'm trying kotlintest, and encounter a similar issue to #312 (kotlintest 3.1.10)
Given test code like:

```
package test

import io.kotlintest.shouldBe
import io.kotlintest.specs.WordSpec

class ThingTests : WordSpec({
    "Thing being tested" should {
        "calculate 1+1" {
            1 + 1 shouldBe 2
        }

        "fail this test" {
            1 shouldBe 2
        }
    }
})
```

The console output is:
```
> Task :test FAILED

test.ThingTests > fail this test FAILED
    org.opentest4j.AssertionFailedError

test.ThingTests > calculate 1+1 PASSED

test.ThingTests > Thing being tested should FAILED
    org.opentest4j.AssertionFailedError
```

This includes 3 PASSED/FAILED messages instead of 2, and I would expect the test name to be "Thing being tested should fail this test" for the failing test

The JUnit test report is slightly better, but does not include the successful tests:
<img width="675" alt="screen shot 2018-11-16 at 14 34 55" src="https://user-images.githubusercontent.com/992153/48624507-d90db100-e9ac-11e8-926a-0ba67286871b.png">

Or is missing the context in the success case:
<img width="673" alt="screen shot 2018-11-16 at 14 45 00" src="https://user-images.githubusercontent.com/992153/48625009-4706a800-e9ae-11e8-9d7b-e3745518df7b.png">

As a comparison, this is scalatest's output with WordSpec
```
[info] ThingTests
[info] Thing being tested should
[info]   + calculate 1+1
[error]   x fail this test
[error]    1 != 2 (ThingTests.scala:13)
```

**Comment by sksamuel** [comment]
The issue is gradle doesn't understand nested tests property.

Although arbitrarily nested tests are supported in Junit 5 platform (which kotlintest runs on, as do some other test frameworks) gradle currently makes the assumption that every test is a method inside a class.

So it gets confused when you have more than one level of nesting (as WordSpec does).

There's an open ticket at gradle:
https://github.com/gradle/gradle/issues/4912

Scalatest uses it's own runner and not Junit platform so avoids this.

**Comment by dhoepelman** [comment]
Thanks for the explanation, let's hope gradle improves their support and makes kotlintest more awesome 😄

**Comment by LeoColman** [comment]
We'll wait forever for gradle to fix this. I'll close this issue and in the distant future perhaps we can integrate with gradle properly.
