### ISSUE TITLE
Why shouldThrow<> {} always pass this check?

### ISSUE THREAD

**Issue by bahka** [kotlintest/kotlintest#479]
In documentation you said:
```
Exceptions
To assert that a given block of code throws an exception, one can use the shouldThrow function. Eg,

shouldThrow<IllegalAccessException> {
  // code in here that you expect to throw an IllegalAccessException
}
```

But in reality it green always

Context: just for fun - green
    Scenario: throw exception - green
    Scenario: no exception - green

```
        context("just for fun") {
            // pass ??? why  
            //  even I set wrong Exception type -   there should be AssertionFailedError
            it("throw exception") {
                shouldThrow<java.lang.AssertionError> { 1 shouldBe 2 }
            }
            // pass ??? why
            it("no exception") {
                shouldThrow<java.lang.AssertionError> { 1 shouldBe 1 }
            }
        }
```

====
If I change  **shouldThrow**<java.lang.AssertionError> to **shouldThrowExactly**<java.lang.AssertionError>  it works well now:

```
 context("just for fun") {
            //  pass
            it("throw exception") { 
                shouldThrowExactly<org.opentest4j.AssertionFailedError> { 1 shouldBe 2 }
            }
            // failed
            it("no exception") {
                shouldThrowExactly<org.opentest4j.AssertionFailedError> { 1 shouldBe 1 }
            }
        }
```

**Comment by Kerooker** [comment]
Thanks for your report!

For the first test, the reason
```
it("throw exception") {
    shouldThrow<java.lang.AssertionError> { 1 shouldBe 2 }
}
```

passes is because `AssertionFailedError` is instance of `AssertionError`. So any `AssertionError` is OK for `shouldThrow`. If you create an Exception such as
`class MyException : AssertionError()`, it will pass `shouldThrow<AssertionError>` as well.

When you change it to `shouldThrowExactly` in the second scenario, you're verifying correctly that it's exactly the same exception you wanted.


However, on your first example:
```it("no exception") {
    shouldThrow<java.lang.AssertionError> { 1 shouldBe 1 }
}
```

And your second example
```
it("no exception") {
                shouldThrowExactly<org.opentest4j.AssertionFailedError> { 1 shouldBe 1 }
            }
```

It shouldn't pass, and you stand correct there.

However, there's one small catch there: This bug will only happen when you're doing it with an AssertionError of some sort, and no other exceptions.

I'll look into it further, but for now this information may be relevant.
