### ISSUE TITLE
Nested TestContext should be disallowed

### ISSUE THREAD

**Issue by dave08** [kotlintest/kotlintest#511]
It took a while to figure out that in `StringSpec` you can't nest tests (there's no complaints in the IDE about it). Also in `FreeSpec`, if one accidentally leaves out the `-`... Would there be a way to warn or disallow such a thing (maybe a DSL mark?)?

Of course, someone that carefully reads the docs will see this, but not everybody bothers to look up something supposedly "obvious" (like me :/ ).

**Comment by Kerooker** [comment]
This makes a lot of sense.

I'll see if it would be possible without refactoring too much

**Comment by Kerooker** [comment]
I don't believe it's possible with the current DSL Marker. As @sksamuel may have already tried, I tried to fiddle with it a little bit.

For instance, let's play a bit with the `FunSpec`, as it has a very simple nested test case to fobid:
```
class Foo : FunSpec() {
    
  init {
    test("This is ok") {
      test("This should be an error") {
          "Foo" shouldBe "Foo"
      }
    }
  }
}
```

If I mark `FunSpeec` with `KotlintestDSL` (a `DSLMarker`), this will indeed be forbidden. However, the situation isn't solved.

```
class Foo : FunSpecWithDSLMarker() {
  val foo = "FOOO"
  init {
    test("This should compile") {
      foo shouldBe "FOOO"
    }
  }
}
```

The above code won't compile anymore. `foo` isn't callable from this scope anymore, as it uses the implicit receiver. I'd have to change it to `this@Foo.foo`, and it's worse than an user forgets a test case.

This scenario escalates to all the other scenarios that we want to forbid nesting, and for the time being we didn't find any solution to this, as we must extend the `FunSpec` class, and it will come with the DSLMarker with it.

I'll try to fiddle with more than one DSL Marker, but I'm not sure it will work.

**Comment by sksamuel** [comment]
DSLMarker won't work.

Let's take StringSpec.

We want to allow people to write `"some string" { }` and so we add an extension method to String.
We don't want this extension method being called from any place, just when we're in the `StringSpec` class so we define it there, and now it's only accessible from instances of string spec.

But when we write a test, the test closure has an implicit receiver of both a `TestContext` (which is a KotlinTest thing), and the outer class, and since the outer class defines the extension method, we can call it again. This means the following works:

```kotlin
class StringSpecExample : StringSpec() {
  init {
    "this is a test" {
       // the next test uses the outer receiver.
      "and another one" { 
       }  
    }
  }
}```

In order to stop an inner closure from accessing functions in an outer receiver, kotlin has `DSLMarker`. This makes two or more receivers marked with the same annotation "hidden" so only the inner most is a receiver.

The two receivers in our case are the class itself `SpringSpec` and the `TestContext`. In order to stop it from being accessible from the TestContext we would have to mark them both with the annotation. But that means we can't access anything in the outer receiver, and so any fields declared are hidden as well.

This is a major limitation of DSLMarker I'm afraid. 

The only other thing we could perhaps is add extension methods to TestContext mirroring the ones in the outer scope, which throw an exception if you try to use them. But that means the TestContext has to know about the various methods all the spec styles declare - not the end of the world but not elegant.

**Comment by sksamuel** [comment]
> I'm not sure if inelegant. 

It's inelegant in the sense that `TestContext` has to be cluttered with copy n pastes of all the methods from the various spec styles. 

It will work though. I'll raise a PR for 3.2 or 3.3 ?

**Comment by dave08** [comment]
Couldn't you just add a check in TestCase that its parent is not a test but only a group and failfast on it? It really is less important to have IDE support for this since a user will get used to the test style and not make the mistake again (which is what happened in my case). The original confusion wastes alot of time (why aren't the tests running..) and may repell a first time user from using this great lib.

**Comment by Kerooker** [comment]
I think we should release 3.2 ASAP, at least the RC. And then start with small increments until 3.3 (3.2.1, 3.2.2...)

**Comment by sksamuel** [comment]
Yes @dave08 that is a great suggestion, didn't think of that.

**Comment by sksamuel** [comment]
StringSpec and FreeSpec now fail at runtime with a nice error when you incorrectly nest tests.
This will be included in RC2 or final, whatever comes next.
