### ISSUE TITLE
shouldThrow behaviour odd

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#70]
The code:
```kotlin
      (name + ": negative argument cause an exception") {
        listOf(-100, -20, -2, -1).forEach {
          shouldThrow<IllegalArgumentException> { f(it) }
        }
      }
````
works entirely as expected. However:
```kotlin
      (name + ": negative argument causes exception") {
        forAll{i:Int ->
          if (i < 0) { shouldThrow<IllegalArgumentException>{ f(i) } }
          else { true }
        }
      }
```
gives a compilation error:
```
Type mismatch: inferred type is IllegalArgumentException but Boolean was expected.
```

**Comment by reckter** [comment]
This is because `shouldThrow()` returns the exception thrown, but `forAll` expects an Boolean as the return type. And as any Exception is clearly not a Boolean, this is intended behavior. 
```Kotlin 
(name + ": negative argument causes exception") {
    forAll{i:Int ->
      if (i < 0) { shouldThrow<IllegalArgumentException>{ f(i) } }
      true
    }
}```

should do what you want.

**Comment by sksamuel** [comment]
What @reckter said. The matchers are not meant to return booleans. Perhaps we need to add another type of property test that doesn't require the function to return boolean, but the absence of an exception is considered correct, like the others do. That is probably more useful for more complicated tests.

**Comment by reckter** [comment]
@sksamuel might be a good idea, had a few cases, where the property test just returned true (Why wouldn't I always use Matchers anyway? 
I mean 
´´´Kotlin
forAll{i:Int ->
      i should be gt 0
    }
´´´
this is the same as this right? (nevermind that this obv. fails for  i <= 0)

´´´Kotlin
forAll{i:Int ->
      i > 0
    }
´´´

**Comment by sksamuel** [comment]
Those examples are the same yeah. Maybe if you wanted to do something more complicated it might be nicer to have both variants.

**Comment by russel** [comment]
`shouldThrow` definitely sounds like a predicate name. It returning the exception rather than Boolean definitely feels to me like a failure of affordance.

**Comment by sksamuel** [comment]
None of the matchers return a boolean to indicate success, they instead throw an exception as that's how junit looks for failures in the tests, so it can't really be changed. Instead we'll add a form of `forAll` that looks for matchers rather than a boolean. Although due to erasure I'm not sure we can call it `forAll` - any suggestions on how to get around that or on a new name?

**Comment by la10736** [comment]
I was thinking that `should` can build a matcher  that throw an exception if its arguments return False. All matchers can return `true` if they pass (an reasonable contract) and chose from to throw an exception or return `false` when they fails. By this way we'll have a flexible tool to build every kind of matcher by combine other matchers.

Anyway kotlin (fortunately) doesn't have checked exception and make a contract where you ask to throw an Exception (`Matcher`) is little bit odd and at least not really clear.

I don't know if it is reasonable or just a crap...

**Comment by sksamuel** [comment]
You need more information from the matcher than false. We could change them to return an Option of Failure.

**Comment by russel** [comment]
Spock definitely manages to have Boolean values expressions in its then and expect clauses and runs on the JUnit4 runner, so it has found how to integrate Boolean expression failure with assertions. However it is based on compile time AST transformation prior to code generation. I guess the question is whether there is sufficient compile time meta programming in Kotlin to avoid a hack. I had assumed Kotlin reified type parameters so as to get round JDK erasure.

**Comment by la10736** [comment]
Of course if you chose to return `false` instead of throw an exception you lose the possibility to make your error message more explicit. You can give two way to build a matcher: return state or throw exception.

My taste is to give an hamcrest like interface to the users that want to write a matcher where you should separate check method from error message but I understand that is an opposite philosophy from how you had chose to implement `Matcher`. So that can be a way to have both of them.... I don't love it (I prefer just one idiomatic way to do a job instead of more) but throw an exception is not what a user is expecting to do.

Finally for fancy matcher like `or` or `any` can chose to catch `AssertionError` and throw a new  exception if need.

**Comment by sksamuel** [comment]
If there's reason to change it, we can change it. I'm open to anything.

But you can't really do this:
```
interface Matcher<T> {
  fun test(value T): Boolean
}
```
Because you lose the error message, and that's far more important (I think) than having matchers be usable in `if`s

**Comment by la10736** [comment]
Yes, but I'm thing to something like 

```kotlin
interface Matcher<T> {
  fun getErrorMessage() = "__default__"
  fun test(value T): Boolean
}
```

Where you can chose to implement `getErrorMessage` function too to return a contextual message. When `should` catch a `false` can take a look if the matcher contain a non default error message and use it, otherwise build a generic one.

**Comment by russel** [comment]
Isn't this heading towards `Option<Matcher>`?

**Comment by sksamuel** [comment]
Let's say we use the Matcher interface suggested @la10736 what's the advantages? The combinability might be one, but we can do that with `Option<Failure>`, or just as I've done in the `and` / `or` matchers by catching the exception. Maybe the exception isn't really that idiomatic for control flow, but I chose it as it fitted in with the way junit worked already.

If we change the matcher specification my preferred would be something like:

```
interface Matcher<T> {
  fun test(value T): Option<Failure>
}
```

But we can have further discussion and as @helmbold will tell you its quite easy to change my mind if you're persuasive :)

I think what @russel wanted, which was the boolean rather than the exception, isn't what `shouldThrow` was designed to do and won't change, but we could add another `doesThrow` or something (better, more boolean-y name required), which returns a boolean true or false. But then it's not so much a testing thing but sugar around an if statement.

**Comment by la10736** [comment]
Ok ... that sounds good to me. IMHO writing tests should be simple so my first concern is to find a way where I can write a custom matcher just by doing the more natural think that pop in my mind: coding the condition.... after that I can refine the message. But thinking to write the negative sentence and throw an exception is not so natural...
But I can fix it simple by build a factory....

**Comment by sksamuel** [comment]
I see, but I think in practice, if you had the getMessage style interface, you'd have to keep state, and then that means its more code and rules out caching matchers or sharing instances. Probably end up more work.

**Comment by sksamuel** [comment]
I've added a Matcher interface that is along the lines discussed here.

```
interface Matcher<T> {
  fun test(value: T): Result
}
data class Result(val passed: Boolean, val message: String)
```

Which allows for combining matchers, `x should (y or z)`.
