### ISSUE TITLE
Extensions like junit rules

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#77]
See https://reddit.com/r/Kotlin/comments/4qmawt/spek_vs_kotlintest/

**Comment by helmbold** [comment]
I like the idea and thought of it myself. However the JUnit 4 extension model is somewhat strange. [JUnit 5 extensions model](http://junit.org/junit5/docs/current/user-guide/#extensions) is much better, although they couldn't resist to use reflection magic. Essentially there are a few extension points:

* BeforeAllCallback
* BeforeEachCallback
* BeforeTestExecutionCallback
* AfterTestExecutionCallback
* AfterEachCallback
* AfterAllCallback

It would be easy to provide similar interfaces and extension points. More interesting would be the question how these callbacks should be registered with a test class. In principle the callbacks are just functions of type `() -> Unit`, so there is no need to have special interfaces.

The actual question how extensions should be combined. It could be the case that one or more provided extensions (from frameworks) should be combined with custom `beforeEach` behavior. This is a syntactical question and question of the correct (or expected) order.

**Comment by helmbold** [comment]
Maybe we should collect some use cases to have a good guidance while designing this API. Use cases would have helped us with tagging, too ... 

If we implement something like the JUnit model, I'd vote for a single extension interface. We could provide default implementations for all methods of the interface, so that an implementer is  not forced to implement all methods if just one is needed.

A Spec class could have a property to provide extensions:

```kotlin
class MySpec : StringSpec() {
  override val extensions = listOf(SpringExentsion, DatabaseExtension)
  ...
}
```

This approach would be the same as for `defaultConfig`. But it could be handy to call a method, so that subclass could add more extensions:

```kotlin
class MySpec : StringSpec() {
  init {
    addExtensions(SpringExentsion, DatabaseExtension)
    ...
  }
}
```

However, I prefer the approach with an overridden property for some reason.

**Comment by helmbold** [comment]
Since the extensions have plug-in characteristic, it would be handy to have a single interface that could be implemented for certain use cases / frameworks.

```kotlin
interface Extenstion {
  fun beforeAll(context: Context) {}
  fun beforeEach(context: Context) {}
  fun afterEach(context: Context) {}
  fun afterAll(context: Context) {}
}
```
A concrete implementation would only override the required methods.

An extension could be registered like this:

```kotlin
registerExtension(exA, exB)
```

I suggest that the extensions are executed before (beforeAll, beforeEach) and after (afterEach, afterAll) according methods of the test class. If there is more than one extension per test class, the order of registration should take effect (from left to right). 

I've left out `BeforeTestExecutionCallback` and `AfterTestExecutionCallback`, because I see no point in having them.

What do you think?

**Comment by sksamuel** [comment]
I think it sounds good. There's the possibility of wanting to know "which" test is executed, and that could only work if we introduce some `TestName` class or similar.

**Comment by helmbold** [comment]
The context seems to be pretty important here. What should go into the context class? 

The JUnit `TestExtensionContext` offers the following:

* TestException
* TestInstance
* DisplayName
* Element
* Parent
* Store
* Tags
* TestClass
* TestMethod
* UniqueId

TestNG offers [much](http://testng.org/javadocs/org/testng/ITestResult.html) [more](http://testng.org/javadocs/org/testng/ITestNGMethod.html) via the [listener API](http://testng.org/doc/documentation-main.html#testng-listeners).

Since the approach is similar to AOP, [AspectJ](https://eclipse.org/aspectj/doc/released/progguide/index.html) could be a source of inspiration, too.

That is pretty much information and without more concrete use cases it is hard to decide what would be actually useful. I suggest that we design a minimalistic context, since it is easier to add something than to remove something.

**Comment by helmbold** [comment]
My idea for the extension mechanism looks like this at the moment:

```kotlin
interface Extension {
  fun beforeAll(context: TestCaseExcutionContext) {}
  fun beforeEach(context: TestCaseExcutionContext) {}
  fun afterEach(context: TestCaseExcutionContext) {}
  fun afterAll(context: TestCaseExcutionContext) {}
}


data class TestCaseExcutionContext(
    val failure: Throwable?,
    val specInstance: TestBase,
    val testCase: TestCase)
```

However, this would be limited to extending a single test classes. It would not be possible to extend the whole set of test classes and their tests directly. What would be the name for this set of all test classes (specs) and their tests? I'm used to the word "suite" for this, but we're already using a suite per spec. 

My vague idea for these "global" extensions is a base class, that a singleton objects implements. The base class would place global settings in a singleton. But this feels somewhat strange and could lead to errors if multiple objects are derived from that base class. Better ideas?

I think of the following example usages:
* start an external application like a database before the first test is run, shut it down after the last test
* use a dependency injection framework and `@Inject` on fields in test classes
* execute certain tests within a transaction
* filter out certain tests

Further examples?

**Comment by sksamuel** [comment]
Some good thoughts.

First off the global extensions. What about using reflection magic to look for a class that derives Extensions, or something. If that class (or more) is found, then the extensions in them are registered. It's a common approach. Bit like Spring finding its classes. Camel finding its routes.

Something like

```kotlin
class MyExtensions : GlobalExtensions {
  addExtension(extension1, extension2)
}
```

I've done this kind of thing before, so I know its not that hard to do. There's a Java library that will find you all the classes of a certain interface / superclass.

Second point, if we have a global extension it needs to be a different interface, one that also supports before/after tests, but also before/after the entire test "suite" is created/destroyed. So it could be subinterface of Extension.

```kotlin
interface GlobalExtension : Extenion {
  fun setup(context: MaybeSomeGlobalContext)
  fun destroy(context: MaybeSomeGlobalContext)
}
```

I think for the contents of `TextCaseContext` (no need to call it TestCaseExcutionContext seems a bit of a mouthful imo), we should add everything we possibly can get a handle on easily - name, class, etc.

Finally, the name for "all the tests". I think suite is more commonly used for a "tests in a file". So we do need another name, and I can't think of anything good at the moment.

**Comment by helmbold** [comment]
After thinking for a while, I consider your suggestion to use reflection for finding the global config the best option. I think `GlobalConfig` is the right name for the according abstract class, since the implementing object would be the right place for adding other kinds of global configuration, too.

```kotlin
abstract class GlobalConfig {
  val extensions: List<GlobalExtension> = listOf()
}
```

The GlobalConfig could be handy to add a usual `Extension` to all specs, but then we would need to wrap an Extension in a GlobalExtension or we'd need another property for global `Extension`s. Or we could have just one interface for all extensions, but this could be confusing. What do you think?

Everything I can think of ("name, class, etc.") should be available via the `TestCaseContext`:

```kotlin
data class TestCaseContext(
    val failure: Throwable?,
    val specInstance: TestBase,
    val testCase: TestCase)
```

The interface for GlobalExtension would look like this:

```kotlin
interface GlobalExtension : Extension {
  fun beforeVeryFirst() {}
  fun afterVeryLast() {}
}
```

What do you think of the method names?

I've no idea for a a kind of context for the `beforeVeryFirst` and `afterVeryLast` methods. But maybe no context is needed here.

It would still be helpful to have a clear naming (glossary) to have sharp definitions of things like "suites", "specs" etc.

**Comment by sksamuel** [comment]
Sounds good, `GlobalConfig` is fine. I don't like the names beforeVeryFirst though. What about just "setup" and "teardown" or start and stop, init or shutdown?

I like the idea of a glossary. Could add a section to the readme.

test = A single test function
spec = A set of tests in a single class file
suite = All the tests in a given source folder (src/test/kotlin)

What do you think? Should suite be a spec, and something else a suite ?

**Comment by helmbold** [comment]
With `beforeVeryFirst` I wanted to make clear that this is not a setup per spec, but a method that is called before the very first test is executed. Maybe there is no good name to distinguish these cases. However, I'm thinking about reducing the `GlobalExtension` interface to just two methods, one before and one after running all tests. And then the naming could be just `beforeAll` and `afterAll` like in a per spec extension. The difference would be context then.

```kotlin
interface GlobalExtension {
  fun beforeAll() {}
  fun afterAll() {}
}
```

Or would you still prefer setup/tearDown?

If we want to allow setting per spec extensions globally for convenience, we could add another property for it. 

Another change ini my design is the type of context for `beforeAll` and `afterAll`, since there is no test result and no test instance.

```kotlin
interface Extension {
  fun beforeAll(context: TestBase) {}
  fun beforeEach(context: TestCaseContext) {}
  fun afterEach(context: TestCaseContext) {}
  fun afterAll(context: TestBase) {}
}
```

What do you think so far?

Let's move the glossary discussion to the forum.

**Comment by helmbold** [comment]
What do you think of "ProjectConfig" and "ProjectExtension" instead of "GlobalConfig" and "GlobalExtension"? Maybe "project" is the word we were looking for (more than a suite/spec).

**Comment by helmbold** [comment]
While implementing this feature I discovered two problematic use cases:

* handling excpetions (for example catching and rethrowing another type)
* measuring execution time of a test, since some sort of state must be kept between `before` and `after` processing

Therefore I'm thinking about replacing `before` and `after` by something like an AspectJ "around advice". However this would not be aligned with the usual `before` and `after` methods of spec classes. These could be replaced by around advices, too, but this wouldn't be as intuitive.

Any ideas/opinions?

**Comment by sksamuel** [comment]
I was never a fan on around advice. Why can't you just assign state in before, and read it again in after?

**Comment by helmbold** [comment]
State would solve the problem with my timer example, but it wouldn't solve the exception handling problem. The code for exception handling looks like this at the moment:

```kotlin
        val callable = Callable {
          performBeforeEach(spec, testCase)
          try {
            try {
              testCase.test()
              performAfterEach(spec, testCase, null)
            } catch (exception: Throwable) {
              performAfterEach(spec, testCase, exception)
              // afterEach would need to rethrow the exception, to gain a failure
              // alternative: throw exception
            }
          } catch (e: Throwable) {
            Failure(testCase.description, e)
          }
        }
```

As you can see, we can decide whether the exception should be swallowed by the afterEach handler or rethrown in any case. 

Both cases could be handled easily and without threading issues with something like around advices.

**Comment by sksamuel** [comment]
Can you show me how the around advice version would look.

**Comment by helmbold** [comment]
With an around advice it would look like this:

```kotlin
val callable = Callable {
    performBeforeEach(spec, testCase)
    try {
        performAroundEach(spec, testCase)
    } catch (e: Throwable) {
        Failure(testCase.description, e)
    }
}
```

`performAroundEach` in the same class ( `TestBase`) would look like this:

```kotlin
  private fun performAroundEach(spec: TestBase, testCase: TestCase): Unit {
    spec.extensions.forEach { extension ->
      val context = TestCaseContext(spec = this, testCase = testCase)
      extension.aroundEach(context)
    }
  }
```

The interface for extensions:

```kotlin
interface SpecExtension {
  fun aroundEach(context: TestCaseContext) {
    context.proceed()
  }
  // ...
}
```

An implementation would look like this:

```kotlin
object Timer : SpecExtention {
    override fun aroundEach(context: TestCaseContext) {
        val startTime = System.currentTimeMillis()

        context.proceed()

        val endTime = System.currentTimeMillis()
        val duration = endTime - startTime
        println(duration)
    }
}
```

For my eyes it is simple an beautiful. The only thing you have to remember is to call `proceed`. But that is the same with AspectJ advices and Servlet filters ...

**Comment by sksamuel** [comment]
Ok exactly like servlet filters, filter.doChain() or whatever it is.

Yes lets do this then.

**Comment by helmbold** [comment]
Ok, fine. Would you go as far as unifying the whole interception/extension model? The Extension interface would look like this:

```kotlin
interface SpecExtension {

  fun aroundEach(context: TestCaseContext, invocation: () -> Unit) {
    invocation()
  }
  
  fun aroundAll(context: TestBase, invocation: () -> Unit) {
    invocation()
  }
}
```

The `beforeAll`, `beforeEach`, `afterEach`, and `afterAll` methods in the specs (actually TestBase) could be replaced by the same two methods. We would avoid two overlapping approaches with then. And we would have to explain only one consistent approach in the documentation. But it would be different than what users are knowing from JUnit or TestNG. 

I see these options:

* only around advices for extensions and spec methods
* around advices for extensions, but the usual before/after methods in the spec. This would lead to the same limitations for before/after (keeping state, handling exceptions) ad mentioned previously. 
* around advices for extensions, around advices and before/after in specs
* offering both, around advices and before/after methods in extensions AND specs. This would lead to redundancy, more concepts to explain and probably somewhat ugly code. But JUnit/TestNG would be familiar with it.

I prefer the first option, but I consider myself somewhat radical sometimes ;-)

What shall we do?

**Comment by sksamuel** [comment]
I think it makes sense to unify it all, keep it the same. Maybe a better word than "invocation" although, perhaps "test" and "suite".

You get into an interesting situation where you might be able to change the receiver for the invocation, allowing people to pass connections, etc, into the test itself.

A typical use case for before and after is to create a db connection and then close it down. 

```kotlin
class MyTest : WordSpec() {
  var connection : Connection = _
  override fun aroundAll(context: TestBase, suite: () -> Unit) {
    connection = create()
    invocation()
    connection.close()
  }
}
```

It's ok except I don't like having to use var fields.

The other option is `aroundAll` could return an object, an instance of `AroundAll` which has multiple methods, including one for handling errors. Ie a bit more like the observer interface in RXJava.

**Comment by helmbold** [comment]
My interceptor implementation (currently on its own branch) works so far. An interceptor looks like this at the moment:

```kotlin
interface TestCaseInterceptor {
  operator fun invoke(context: TestCaseContext, callable: () -> Unit) {
    callable()
  }
}
```

I'll try to reduce it to a simple function (what it is already effectively). As you can see, I've splitted the interface for TestCase and SpecInterceptors, because chaining a combined interceptor and applying the chain to either a testCase or a spec, wouldn't make much sense. 

And I want to add interceptors to the `config`, so that it is possible to add interceptors only to certain testcases. But then it could make sense to move the TestCaseInterceptors to the Spec config object as well, to keep it consistent. However, per spec interceptors would remain in the class as a property. Does this make sense to you?

My plan is to introduce a `ProjectInterceptor` that runs before the very first and after the very last test. But there is no such thing as "project" in terms of JUnit. JUnit just picks some Spec first and executes it. There is nothing that could actually be wrapped, but maybe I can find a workaround that make it look like a usual interceptor.

**Comment by helmbold** [comment]
Do you have an idea how an `ProjectInterceptor` could be implemented? I have currently no idea, since JUnit looks up tests by reflection an just starts with an arbitrary test.

**Comment by sksamuel** [comment]
What's the method signature for project interceptor at the moment ?

**Comment by helmbold** [comment]
Since there is no context, it is only:

```kotlin
  fun interceptProject(project: () -> Unit) {
    project()
  }
```

This could be reduced to a pure function type (`() -> Unit`).

**Comment by sksamuel** [comment]
Ok, so what is it you're asking. How to find instances of it?

**Comment by helmbold** [comment]
Yes, the question is how to find a "project instance". As far as I know there is no such thing in JUnit. Getting a test case instance is simple, getting a spec instance is simple ... but how to get a project instance?

**Comment by sksamuel** [comment]
Ah ok. Well you need to use this library.
https://github.com/ronmamo/reflections

Which allows you find instances. So we'll tell people to do this:

```
object MyProjectConfig extends AbstractProjectConfig {
 fun ...
}
```
And then using that library we find them on the classpath. It's a technique I've used before.

**Comment by helmbold** [comment]
I'm already using this library to find the project config, but what I need is the "project" to be executed. If it were a hierarchical data structure it would look like this:

* project
  * spec 1
    * test case A
    * test case B
  * spec 2
    * test case A
    * test case B
    * test case C

The I could wrap the whole callable project in an interceptor like I do with test cases and specs. But there is no such instance (as far as I know) that is a container around all specs.

**Comment by sksamuel** [comment]
Right I see. The KTestJUnitRunner is invoked for each file I think. So we might be scuppered. 

One possibility, is that you have a singleton object. The first time KTestJUnitRunner is created, in the constructor, invoke ProjectConfig there if you haven't invoked it already. 

Not sure how you'd go about knowing when it's finished though. And without that you can't really do your around advice.

We might just have to drop the idea of project interceptors.

**Comment by helmbold** [comment]
I'm still looking for a project interceptor solution, but if I find no way, I'll stick with the before/after approach in this case.

While developing the tests for the interceptors, I discovered the need for adding certain config properties instead of overriding them. Lets say we had a spec with a default config:

```kotlin
class MySpec : StringSpec {

  override val defaultTestCaseConfig = config(tag = TagA, interceptors = listOf(interceptorA))

  "should do something" {
    ...
  }.config(tag = TagB, interceptors = listOf(interceptorB) // would override tags and interceptors from above
}
```
So, I had the idea to introduce "additional" parameters, which would add the arguments to the exsisting arguments instead over overriding them.

```kotlin
  "should do something" {
    ...
  }.config(additionalTag = TagB, additionalInterceptors = listOf(interceptorB))
```
In this example the test case would effectively have the tags `TagA` and `TagB` and the interceptors `interceptorA` and `interceptorB`. This is pretty much the same behavior as in annotation driven frameworks like JUnit, where (some) annotations at class level are inherited by each test case and where each test case can have additional annotations.

What do you think @sksamuel ?

**Comment by martin-g** [comment]
Which version of JUnit do you use ?
I don't see anything in build.gradle but kotlintest/src/main/kotlin/io/kotlintest/KTestJUnitRunner.kt depends on it somehow.
IMO it would be better to use JUnit 5.x alphas and use the new extensions mechanism.

**Comment by helmbold** [comment]
The new JUnit extension model doesn't fit well with our programming model and is needlessly complicated (e. g. Store). Maybe we could introduce an adapter later, to be able to reuse existing extensions for frameworks like Spring.

**Comment by helmbold** [comment]
@sksamuel What do you think about the `additional*` config params? If I would introduce it, I would remove the `tag` (singular) parameter to avoid confusion and too many parameters (otherwise I would have to introduce `additionalTag` to be consistent).

Btw: I see no solution for project interceptors with JUnit. We could do it with [TestNG](http://testng.org/javadocs/org/testng/TestRunner.html), I think, but that would be a major change now. However, I still have problems to run KotlinTest tests in IntelliJ, so if we should change the underlying test runner we could take the opportunity to introduce project interceptors.

**Comment by sksamuel** [comment]
Not sure if additional is really that important. Tags are not used that much, just the odd "integration" or "mongo" type tag. So people can easily repeat them?

As for interceptors - what about Junit 5. That has them?

**Comment by helmbold** [comment]
I agree, that we don't necessarily need the "additional*" parameters. If someone misses them, we could introduce them later. However, I tend to remove the `tag` (singular) parameter, since it is a bit inconsistent. It is not clear, whether it overrides the other tags (what would be consistent) or not (what actually happens). 

JUnit 5 dosen't have interceptors.

**Comment by helmbold** [comment]
I consider the extensions/interceptors complete now. The only remaining thought is to split the interface `ProjectExtension`. 

```kotlin
interface ProjectExtension {
  fun beforeAll() {}
  fun afterAll() {}
}
```

Interceptors and extensions in a list are executed from left to right. But if you think of the before/after methods as pairs, the afterAll methods must be executed in reversed order, what is a bit counter intuitive. Any thoughts @sksamuel ?

Please have a look at the code and documentation so far (branch: feature/#77_extensions). Do you find the documentation clear?

**Comment by sksamuel** [comment]
Overall very nice. A couple of thoughts thought.

1. Do we need to have the ProjectConfig object. Why not just find _all_ ProjectExtensions on the class path?

2. Would it be nice if in a test spec interceptor, you could decide which tests should run or not? You'd need to pass in a collection of "tests" which the user could filter and then pass to an "executor".

**Comment by helmbold** [comment]
1. I prefer an explicit ProjectConfig, because:

* it is more obvious what  the actual config is
* the order of extensions might be important (and can not be controlled with a reflection scanning approach)
* there could be unwanted extensions on a class path (from libs/frameworks)

2. Good idea,  I'll try to implement it like that.

Do you see any drawbacks in splitting the ProjectExtension interface?

**Comment by helmbold** [comment]
I created a separate ticket #106 for passing the list of test cases to the spec interceptor.

**Comment by helmbold** [comment]
Done and merged to 2.0 branch. https://github.com/kotlintest/kotlintest/pull/107

**Comment by sksamuel** [comment]
@helmbold I'm just doing some work on tickets #111 #112 and I notice that no tests complete in intellij now. By complete I mean the status in intellij doesn't change, it either says ignored, or stays with the yellow in progress circle. I think maybe something in the interceptor work broke it? Can you confirm you see the same thing ?

**Comment by helmbold** [comment]
@sksamuel Same here. I've never associated that with interceptors until now.

**Comment by sksamuel** [comment]
Shall I leave it to you to see what broke it or do you want me to have a go ?

**Comment by helmbold** [comment]
I'll have a look.

**Comment by helmbold** [comment]
I've created a separate issue: #114
